### ISSUE TITLE
Opera GX Support

### ISSUE THREAD

**Issue by zuils** [doshidak/showdex#12]
The extension that allows you to install chrome extensions on opera gx just doesn't load on showdown. I can install it but the showdex tab doesn't appear.

**Comment by doshidak** [comment]
Hey @zuils,

Just wanted to quickly update you on my findings.

Is the Opera extension you were talking about called [Install Chrome Extensions](https://addons.opera.com/en/extensions/details/install-chrome-extensions/)? Apparently, users are saying that that extension is for older versions of Opera and the newer ones allow you to just add the extension from the Chrome store directly.

![opera-install-chrome-extensions-screenshot](https://user-images.githubusercontent.com/18254287/189791306-fe26b4bc-2ee2-4e13-9381-3fc5fde51add.png)

I just went on our [Chrome Web Store](https://chrome.google.com/webstore/detail/showdex/dabpnahpcemkfbgfbmegmncjllieilai) page on Opera GX and clicked on the "Add to Chrome" button. Opera GX handled the rest right out-of-the-box without any additional Opera extensions.

![opera-gx-extensions](https://user-images.githubusercontent.com/18254287/189791210-5f6906b7-4312-45c7-b0ac-fc451c4002b0.png)

Opening Showdown, the Hellodex appears as intended.

![opera-gx-hellodex](https://user-images.githubusercontent.com/18254287/189802468-593fa1d0-50f6-4c0c-8157-60e26a62d085.png)

Spectating a game, the Calcdex appears as intended with all the Pokémon and downloaded sets loaded in.

![opera-gx-calcdex](https://user-images.githubusercontent.com/18254287/189800887-44365142-71e7-47ee-be37-3bd6a0576a3d.png)

Could you try installing the Showdex extension directly through the Chrome store on Opera GX and let me know how that goes? We'll still put the extension up on Opera Addons to avoid this confusing installation process.

Thanks!

**Comment by zuils** [comment]
Ok I'll test that a bit later, got some stuff to do rn, I'll keep you updated when I get around to doing that!

**Comment by zuils** [comment]
Got it to work, thanks for the help!
