### ISSUE TITLE
FFA support?

### ISSUE THREAD

**Issue by Legend-Recalls** [doshidak/showdex#125]
since it was implemented in 1.1.3, i thought there wd be a way to switch opponent in FFA match, but I cant see anything like that, is it not implemented yet or am I missing anything?
![image](https://user-images.githubusercontent.com/69719681/218092209-d012575e-7699-429d-bb33-655a2bf2913b.png)

**Comment by doshidak** [comment]
DAMNNN I may have butchered the part where I hide the user selection dropdown if you're a player in the battle. Looks like it completely hides the dropdown for both sides when it should only be on the bottom side (i.e., your opponents). Oops.

I'll go ahead and get this fixed. I know you've been waiting on FFA for a while, so sorry about that :c

**Comment by Legend-Recalls** [comment]
is this project still in work?

**Comment by doshidak** [comment]
Yes! Sorry! We took some time off to take care of some life things, so we haven't been able to work on Showdex for awhile. We're back on the grind now though, so I'll make sure this is fixed with the upcoming release.

**Comment by doshidak** [comment]
We're rushing to get a release out (v1.1.5) with just bug fixes soon in the coming weeks (especially cause Tera detection is broken again, apparently), which will include a fix for this as well.

I really, really do appreciate your patience with this, I know it's been *months*. (...Time flies :c)

**Comment by AhmedA1559** [comment]
Just a quick input about this while this is up on the table, but I feel that it might be better to allow both sides to switch. Locking it to just the user player on one side might be too limiting, as it prevents users from doing calcs between 2 different other players (which might be useful in FFA format or 2v2 multi format, where some users might find it pivotal to do calcs between 2 other players).

**Comment by doshidak** [comment]
Hey guys, just sending an update your way!

Finished (& tested) FFA support; the dropdowns should appear regardless if you're playing or spectating now. This will be bundled with the v1.1.5 release!

**Comment by AhmedA1559** [comment]
Will the changes be pushed to GitHub before the release?

**Comment by Legend-Recalls** [comment]
> to take care of some life things, so we haven't been able to

lol I see take care man


> Just a quick input about this while this is up on the table, but I feel that it might be better to allow both sides to switch. Locking it to just the user player on one side might be too limiting, as it prevents users from doing calcs between 2 different other players (which might be useful in FFA format or 2v2 multi format, where some users might find it pivotal to do calcs between 2 other players).

definitely agreed



> Hey guys, just sending an update your way!
> 
> Finished (& tested) FFA support; the dropdowns should appear regardless if you're playing or spectating now. This will be bundled with the v1.1.5 release!

waiting eagerly! 🤞
