### ISSUE TITLE
Can't calc if I change into mega/new form

### ISSUE THREAD

**Issue by zuils** [doshidak/showdex#142]
Can you add a button or something that allows you to calculate with a certain form, like zacian turning into zacian crowned. Or mega evolving?

**Comment by doshidak** [comment]
Heya!

If the Pokémon has an alternate forme available (like *Zacian-Crowned* or a Mega forme), you'll be able to click on the name to bring up the forme switcher, as shown below:

![showdex-v1 0 7-formes-switcher-20221112](https://github.com/doshidak/showdex/assets/18254287/785bd713-89b2-4e2b-b999-6f8e0d439de5)

> ^ Actually a screenshot from an older version of Showdex, but it's more or less still the same.

The Pokémon's forme will switch back to the one reported in-battle during a battle sync, so you don't have to worry about making sure to switch back its forme or anything.

I know it's not very apparent you can do this in the UI, but we plan on adding some visual indicator in an upcoming version to let you know when there are available formes to switch to.

Let me know if this answers your question! (...or if I totally misunderstood LOL)

**Comment by zuils** [comment]
Alright, maybe you can add an indicator you can click on it because I never thought about clicking on it
