### ISSUE TITLE
BUG: Import not setting Ability of Pokemon

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#154]
Here's an example set off Showdown:
```
Tentacruel @ Leftovers
Ability: Liquid Ooze
EVs: 252 HP / 120 SpD / 136 Spe
Calm Nature
- Rapid Spin
- Surf
- Toxic
- Ice Beam
```
Here's what Showdex imports as:
![image](https://github.com/doshidak/showdex/assets/15176546/ebd94313-49ca-4865-9745-a89da34caf32)

Note that it has Clear Body instead of Liquid Ooze

**Comment by doshidak** [comment]
Nice catch! Definitely should be set to *Liquid Ooze*, even if *Clear Body* was revealed (in which case, a "RESET" button would appear next to the "ABILITY" header).

I'll look into this, thanks!

**Comment by doshidak** [comment]
found the bug & fixed!

but note that if the Pokémon's ability has been revealed, it won't matter what ability was specified in the PokéPaste (it'll always set it to the revealed ability).

thanks!! c:
