### ISSUE TITLE
My location does not apply to spectating battles

### ISSUE THREAD

**Issue by Knepsia** [doshidak/showdex#160]
when you select your location as top/bottom, it is not followed when spectating, the hover text implies there's a default behavior, but it can be overridden

**Comment by doshidak** [comment]
Hiya!

Sorry if the language used in that setting wasn't clear, but the "*My*" in *My Location* implies that you're playing a battle, so when you're spectating, the setting does nothing. The "default behavior" part refers to the "Auto" setting, which is to use the order that's in Showdown, so player 1 will be top, player 2 bottom. (I'll add some clarification to that setting tho.)

Let me know if that answers your question c:
