### ISSUE TITLE
gen 1 all pokemon show as 0 stat exp

### ISSUE THREAD

**Issue by Tree69420** [doshidak/showdex#163]
![image](https://github.com/doshidak/showdex/assets/65974506/8439f082-b6c8-432c-bf68-c4cdddb2ae13)
![image](https://github.com/doshidak/showdex/assets/65974506/5056ad23-ee05-4e7e-82a5-45659469c05c)

**Comment by doshidak** [comment]
good catch! thanks for letting me know c:
