### ISSUE TITLE
Showdown Usage sets have been a little wonky over the last month or two

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#174]
I'm getting real odd Showdex estimates for opponents, like 0+ SpAtk Suicune:
![image](https://github.com/doshidak/showdex/assets/15176546/97402c14-91d1-4f70-b528-ffdce114225b)

(Apologies for the .zip, seems that showdown replays for the last 4 years are all lost, and we can't upload new ones right now)
[replay suicune.zip](https://github.com/doshidak/showdex/files/13531446/replay.suicune.zip)

-----

I don't have a replay for it, but I also went up against a Showdex estimated 252- Speed Swampert

-----

I'm playing from Microsoft Edge, in Incognito Mode

**Settings export:**
```
v:1.1.9;@:showdex-v1.1.9-b18BE0E2279A.chrome;#:18C26F58462;$:settings;fc:dark;dm:n;hd:oos~y|frr~n|sbr~y|sdb~y;cd:oos~always|oas~showdown|oop~showdown|con~battle-tab|doc~y|das~y/y/y/y/y|spr~y|aps~top|snn~n|osp~y|sao~n|ssf~n|snd~y|dsp~y|drp~y|dus~y|mpa~1|pus~y|itb~always|ats~y|aeo~n|dam~n/y/y/y/y|fnv~y|lut~n|rdb~y|ept~always|sme~meta|sbs~meta|sle~n|lgv~base,iv,ev/iv,ev,base/iv,ev,base/iv,ev,base/iv,ev,base|ais~meta|sut~y|sat~y|sit~y|smv~y|smu~y|pmd~y|sda~nfe|fda~y|cmd~y|sft~y|ncl~#4CAF50/#CCC800/#FF9800/#F44336/#F44336|nlb~1HKO/2HKO/3HKO/4HKO;sd:aas~n
```

**Comment by doshidak** [comment]
ah did find an issue there, nice catch!

*Suicune*'s top Gen 3 OU spreads from pre's API are:

```jsonc
// https://pkmn.github.io/smogon/data/stats/gen3ou.json

{
  "Suicune": {
    /* ... */
    "spreads": {
      "Modest:28/0/0/252/0/228": 0.1083,
      "Bold:240/0/252/0/0/16": 0.0817,
      /* ... */
    }
  }
}
```

ya the sets application routines have been a bit wonky for sure after the sync rewrites I did back in v1.1.7 (hopefully they continue to work as intended!), but guess now I'm selecting the second spread after our new spreads feature in v1.1.8 v__v

thanks!

**Comment by doshidak** [comment]
oh forgot to mention, but for now, guess you can apply the first spread when you click on the "SPREAD" button next to the natures dropdown. I know that's annoying, but unfortunately is the only workaround for now :c
