### ISSUE TITLE
brick break breaking screens isn't accounted for

### ISSUE THREAD

**Issue by Elitemagikarp** [doshidak/showdex#175]

**Comment by doshidak** [comment]
ah nice catch! I was able to verify that this is the case also in [calc.ps](https://calc.pokemonshowdown.com). appears to be an issue with the calculation mechanics itself (& not Showdex), so while this is something we can address on our end, think it might be better to move this upstream to the [`@smogon/calc` repo](https://github.com/smogon/damage-calc) perhaps?

but if you have no luck getting your request thru (or you're told to toggle the screens off yourself), let me know & I'll see what I can do lol.
