### ISSUE TITLE
BUG: Showdex thinks I'm a spectator after disconnecting/reconnecting

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#186]
Halfway through the match (Turn 14), my connection got spotty and so I refreshed the page, then got prompted and also had to click the showdown `Reconnect` button.
![image](https://github.com/doshidak/showdex/assets/15176546/bfdd7d1d-1161-46f2-8db2-c2363122b455)

The screen redrew a 1 or more times, and once I got everything rendering again, it put my pokemon on the bottom of Calcdex instead of the top. Notably, it also stopped reading my moves/stats, and instead went with a guess like it does for opponents.

Here's a replay:
https://replay.pokemonshowdown.com/gen3ou-2041712987

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.2
**Format, if applicable:** ADV OU

**Comment by doshidak** [comment]
ah that may be due to a race condition I've discovered in v1.2.2 with Showdex initializing & Showdown logging you in. I've done some changes to address this in v1.2.3, so if the issue still persists, feel free to reopen this issue or make a new one.

thanks!
