### ISSUE TITLE
BUG: Unsetting rain is not reducing Kabutops speed from Swift Swim

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#191]
I can't get the opponent's speed down to base even if I change or reset the weather, or even refresh the page: 
![image](https://github.com/doshidak/showdex/assets/15176546/ad13b8f7-5cfb-40e9-a9b1-68edd2e41726)

Rain ends on the next turn, I can find that Kabutops should be slower than my Dugtrio by using showdown calc, but unfortunately I cannot do so here

Once the turn advanced and the rain stopped in-game, speed calculation went back to normal

https://replay.pokemonshowdown.com/gen3ou-2050697419

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** ADV OU

**Comment by doshidak** [comment]
nice find! thanks for the report! c:

![calcdex-dirty-weather-swift-swim](https://github.com/user-attachments/assets/1cff4e55-e3b8-461f-b2e6-d06765b536db)

(...also that was one wild replay ngl)

![whos-dirty-dan](https://github.com/user-attachments/assets/75fb4fd2-91e5-40c4-b45b-6ecb3c144d1f)

LOL

**Comment by doshidak** [comment]
oops forgot to mark this as fixed w/ #212
