### ISSUE TITLE
show smogon dex sets before sets in teambuilder

### ISSUE THREAD

**Issue by Elitemagikarp** [doshidak/showdex#193]
it's annoying to have to scroll down to select the most common sets when trying to figure out an opponents' set

**Comment by real-F-00** [comment]
that's true, i would suggest adding a toggle in the settings

**Comment by ammo414** [comment]
i agree -- I have many sets in teams that other folks would describe as "poopy". I would rather they not show up as the first set on an opponent's pokemon.

**Comment by doshidak** [comment]
we'll cook somethin up for this, thanks for the suggestions y'all <3
