### ISSUE TITLE
BUG: Cannot increase attack stages after winning while Intimidated

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#195]
Note that the game state ended with my Zapdos intimidated by Gyarados
![image](https://github.com/doshidak/showdex/assets/15176546/52a7744f-ee07-41bb-ac7a-4fc32b77834a)

However, while seeing what a physical spread might do for Zapdos, I tried to click the `+` to increase my attack stage.
Instead, I can only lower it to -2, -3, etc. It won't respond when I try to push it over 1, while in the game finish state.

I have not extensively tested this in other game states yet, but it makes post-match analysis difficult.

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** ADV OU
**Replay:** https://replay.pokemonshowdown.com/gen3ou-2081936986-419y9020drzbblt5w5ec3na4qwt6mllpw

**Comment by doshidak** [comment]
ya we've fixed this one... hopefully LOL. it'll be part of this upcoming version!
