### ISSUE TITLE
Calc applies Tera <60BP power boost and Sheer Force in the wrong order

### ISSUE THREAD

**Issue by Sauzels** [doshidak/showdex#198]
![Screen Shot 2024-03-27 at 2 38 19  PM](https://github.com/doshidak/showdex/assets/20540950/3b4abb66-da5b-4b25-968d-019219735361)
Sheer Force applies before the Tera boost checks if the move is under 60BP, so Feraligatr's Trailblaze should be 65BP, not 78.

**Comment by doshidak** [comment]
hey sorry for the late reply! we've disabled this on our end to let the underlying [Damage Calculator](https://github.com/smogon/damage-calc/tree/master/calc) handle it instead. this change will be available in this upcoming version, dropping real soon.

thanks for your patience! c:
