### ISSUE TITLE
Tera Starstorm vs Terastallized Pokemon

### ISSUE THREAD

**Issue by MonoHearted** [doshidak/showdex#204]
Seems like clicking Terastallize incorrectly updates calcs for Tera Starstorm damage against Terastallized enemy Pokemon (as it should be super effective.)

![image](https://github.com/doshidak/showdex/assets/7800801/d60dbff6-2b73-4b69-a53b-93f6c1e8d9a0)
![image](https://github.com/doshidak/showdex/assets/7800801/26b469a1-3f88-4131-8774-56964127c7d0)
![image](https://github.com/doshidak/showdex/assets/7800801/82ecb4a9-0c39-49b4-bf4d-c394df59d48b)

**Comment by analogcam** [comment]
This is fixed now.
