### ISSUE TITLE
[BUG]: Agil passed into a mon that got paralyzed, paralysis is not lowering calcdex's speed

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#206]
Calcdex is showing a speed of 274, which is incorrect:
![image](https://github.com/doshidak/showdex/assets/15176546/9d1b36ff-b23f-4334-8e51-20b4b754ff25)

Attempting to unset/reset paralysis, change mons, or adjust speed up/down is not fixing the issue

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** `[Gen 3] OU

**Comment by doshidak** [comment]
nice catch! thanks c:
