### ISSUE TITLE
[BUG] Honkdex wont show me effect from increasing/decreasing speed

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#208]
I'm in the team builder, and decided to use Honkdex as a scratch space
Heracross is pictured here, but changing +/- speed stat changes is not changing the speed from 295:
![image](https://github.com/doshidak/showdex/assets/15176546/c1096152-3e92-47d0-a937-0147b9111ebb)

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** `[Gen 3] OU

**Comment by jmynes** [comment]
This is probably connected to this and other similar bugs:
https://github.com/doshidak/showdex/issues/206

**Comment by doshidak** [comment]
ah this one's not as obvious, but it appears in your screenshot that side B has no Pokémon. in those instances, the Honkdex won't perform any calcs (including stats) until there's an opposing Pokémon to calc against, just as a performance optimization.

lmk if that solves your issue!
