### ISSUE TITLE
Gen 1 and 2 stats are wrong

### ISSUE THREAD

**Issue by zuils** [doshidak/showdex#6]
Gen 1 and 2 pokemon stats have 252 evs in every stat, the calc does not have that and adding more evs just crashes it for some reason

EDIT: Also, gen 1 and 2 calcs stats with dvs (0-15) and doesn't multiply the base by 2 in the stat formula

**Comment by doshidak** [comment]
There's no support for DVs atm, but I'll add that to the pipeline. I'll keep this issue open until I implement this.

Thanks for your report!
