### ISSUE TITLE
Shift + arrow keys to move the room tab from Showdex home page

### ISSUE THREAD

**Issue by singiamtel** [doshidak/showdex#70]
Sorry to bother again, but could we have shift+arrows move the room tab like it does with the regular rooms? 

Thanks again!

**Comment by doshidak** [comment]
Hey there again! No worries haha.

Didn't know shift+arrow keys were a thing either LOL. I'll see if I can squeeze this in with the upcoming patch.

Thanks!

**Comment by singiamtel** [comment]
Wait until you hear about ctrl shift arrows...


I'm kidding of course lol

**Comment by doshidak** [comment]
LOL you got me there for a sec hahah. I was like bruh, I just finished implementing this and you're telling me there's more?!

Anyways, I got this working so expect to see it in the upcoming release (coming *very* soon)!

\ (•◡•) /

**Comment by singiamtel** [comment]
Thank you much!
