### ISSUE TITLE
have random battle tooltips show possible moves

### ISSUE THREAD

**Issue by pistolius** [doshidak/showdex#87]
When you mouse over the opponent pokemon it would be cool if it could show the results of the /randbats command there so you dont have to run it manually :D

**Comment by doshidak** [comment]
Hi there! Thanks for your suggestion! :)

We actually display the possible abilities, items, and moves (along with their probabilities) in their respective dropdowns, as you can see from the screenshot below. Possible options are under the "**POOL**" category.

<img alt="calcdex-randbats-pool" width="792px" src="https://user-images.githubusercontent.com/18254287/207759418-300518d5-b999-47bf-a7cd-22f41ffa8571.png" />

Showdex aims to keep the Showdown UI as vanilla as possible, so you can use this alongside the [Randbats Tooltip](https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-randbats-tooltip.3686306) extension if you'd like this data in the tooltips. (I believe **pre**, the person behind this extension, is pushing out Gen 9 support soon.)

Let me know if this addresses your issue!

**Comment by doshidak** [comment]
Assuming this has solved your issue, so I'll go ahead and close it for now.

Feel free to open another one if you have any other questions/suggestions!
